Focus 2.2 “He came unto His own…”
Jesus’ emergence into public life


= Unit 1: ‘I came forth from the Father…” – the pre-existence & nativity of the God-man

= Unit 2: “…and have come into the world…” – 3½ years of preaching the Kingdom of God is come


[NOTE]
====
Jesus’ emergence into public life; Initial crises and ministries in Judea & Samaria;
Jesus is gaining the attention of the nation. Initial crises and ministries in Judea & Samaria
====

[TIP]
====
This period is often denominated “The Early Judean Ministry of Jesus,” but that title is not accurately descriptive of the role played by this period in the ministry of Jesus.
====


. The first five days of the Public Ministry of Jesus
+

[CAUTION]
====
++++
<a href="https://slides.cypressbible.org/app/#18" class="harmony-event-link">Harmony Event #18</a>
++++
====
+

.. DAY 1: The Baptist's first identification of Jesus as Messiah (Jn 1:29-34)
+

NOTE:
+

- Recall that the ANCHOR DATE for the list of days in Jn 1:29 thru 2:1 is Jn 1:19-28 – the interrogation of John by a Sanhedrin committee
- The time setting:
+

[NOTE]
====
Note: recall the relationship between this section of the 4th Gospel and the Synoptics
====
+
- The essence of the Baptist's testimony in this passage: "I have been long time telling you that Messiah was soon to come; I swear to you that his Jesus of Nazareth is He!"

- These verses (Jn 1:29-34) constitute an official statement, made under self-imposed oath, concerning the identity of this Jesus of Nazareth.

- From all that we know of this day--the spirit of anxious expectation with which Messiah was awaited, the oft appearance of false messiahs, the distorted concept of Messiah which had become so popular, and the excitement generated by two miraculous births and then by the ministry of the Baptist--it is not difficult to understand why such a careful and emphatic designation of the true Messiah was felt necessary.
+

But beyond all of that there is the reality that in many very important ways – including His physical appearance – Jesus of Nazareth terribly disappointed the messianic longings of the Jews of His day.
+

- This record of John's testimony on the day after the 40-day temptation is intended to be representative.  That is, this is the testimony borne by John the Baptist everywhere he went after he had baptized Jesus.

... Notice the ways in which John lends strength to his testimony concerning Jesus the Christ:

.... He appeals to his earlier testimony (1:30).
+

[NOTE]
====
That is, John is careful to remind his hearers--mostly those who had accepted his message and been baptized by him--that he had been for several weeks announcing the soon-coming Messiah.  They had received that message.  Now, that same messenger is revealing the Messiah; it behooves his listeners to receive this testimony as well.
====
+

.... He carefully discounts the possibility of any collusion between himself and this One whom he is identifying as the Messiah (1:31,33).

.... He deliberately casts his testimony in the form of a solemn oath, such as would be given before a judge in a court of law (1:32,34).

.... He appeals to the heavenly testimony as to the Messianic identity of this Jesus: he calls God to witness on behalf of his statement (1:32).

.... He reminds his hearers that the identity of this One had been specially revealed to him by God (1:33).
+

[NOTE]
====
THE POINT:  This is a solemn testimony, issued by the Forerunner in the presence of witnesses, and reinforced carefully by appeal to other evidences.  The essence of this testimony: "Behold - there He is!  That is the Lamb of God, the One of whom I have been speaking, come to take away the sin of the world!"
====
+

[TIP]
====
Important question: Why did John see it as so important to reinforce his message so carefully and so dramatically?
====
+

... Notice what John the Baptist reveals here concerning the person and work of the Messiah
+
- He is the "lamb of God, which taketh away the sin of the world!" (1:29)
- "After me cometh . . . he was before me!" (1:30)
- "The same is he which baptizes with the Holy Ghost."  (1:33)
- "This is the Son of God!" (1:34)
+

.. DAY 2: The gathering of Jesus’ first disciples [apostles-to-be] (Jn 1:35-51)
+

[CAUTION]
====
++++
<a href="https://slides.cypressbible.org/app/#19" class="harmony-event-link">Harmony Event #19</a>
++++
====
+

NOTE:
+

- The time setting of this narrative:
- The background of this passage: John the Baptist is carefully instructing those who had followed him to now follow Jesus (1:35-37).
+

We may assume that the testimony and instruction which John gives here was given many times, as the Messiah whom John had come to announce had now arrived.

- There were undoubtedly multitudes who identified with Jesus at this time, men and women who had already accepted the message of John the Baptist and now were happy to believe his testimony that this Jesus of Nazareth was indeed the Messiah whose soon arrival he had been heralding.

- Important notes regarding this period of Jesus’ ministry when He is gathering to Himself the disciples of John the Baptist (cf. Jn 3:21ff.)

* With regard to Jesus’ immediate ministry: the significance of Jesus traveling with disciples


* With regard to the later ministry of Jesus: the significance of committed disciples scattered throughout the land


* With regard to the fact that the Synoptics all neglect to record these months of Jesus’ ministry


- Note the disciples gathered in this pericope and reflected in the one following:

* As stated above, this record is representative of several weeks or months of ministry of John the Baptist and of Jesus.

b)These 5 (or 6) disciples are probably mentioned because with the passage of time they become part of the 12 apostles, and we get to know them quite well.

c)The disciples gathered in 1:35-39

ANDREW, brother of Simon Peter – named in 1:40

JOHN the apostle, brother of James, son of Zebedee – unnamed, but conjectured b/c he is reluctant to identify himself in his Gospel (cf. 13:23; 19:26; 20:2; 21:7, 20, 24)

PETER the apostle – fetched by Andrew, brought to Jesus, given the nick-name Peter [Grk] / Cephas [Aramaic] by Jesus

d)PHILIP the apostle (cf. Mt 10:3), native of Bethsaida (on Sea of Galilee) – part of the group in the next pericope, evidently gathered to Jesus as were the 3 above, brought Nathaniel to Jesus (1:43-44)

e) NATHANAEL the apostle (cf. Mt 10:3 – known there as Bartholomew) – wonders if anything worthy can come from Nazareth, supernaturally known by Jesus (1:43-51)




#20 3b.DAY 3-5: Emergence into public notice - the miracle at Cana
(Jn 1:43 – 2:11)

NOTE:
1)Re: the time notation of 2:1
a.What happened on Day 3?

b.2:1 = the 3rd day after what?

c.The wedding in Cana – on Day 5 or Day 6?


2)This was doubtless a family wedding. Thus Jesus was “invited” (2:2), and it was appropriate to bring His “disciples” as well.

3)Concerning the importance of weddings in C1 Jewish culture


4)Important: every indication is that this is the first time Jesus has seen His mother since He left Nazareth some months ago to go to be baptized by John.

In that regard, what has changed since Mary last saw her son?


1c.The narrative itself

1d.The dilemma - the wine had been completely consumed before the days of feasting were expired (2:3a)


"None but those who know how sacred in the East is the duty of lavish hospitality, and how passionately the obligation to exercise it to the utmost is felt, can realize the gloom which this incident would have thrown over the occasion, or the misery and mortification which it would have caused to the wedding pair."
  Farrar, 76)

2d.The initial conversation between Mary and Jesus (Jn 2:3-5)

1e.Why did Mary approach Jesus concerning this matter?



2e.The reply of Jesus to Mary (2:4,5) is not nearly so harsh as it sounds in our translation.











1)The term of address - "Woman"

"He does not call her `mother' because, in circumstances such as these she was His mother no longer; but the address, `Woman,' was so respectful that it might be, and was, addressed to the queenliest, and so gentle that it might be, and was, addressed at the tenderest moments to the most fondly loved."
Farrar, 77


2)The rebuke - "What have I to do with thee?"

"Almost all commentators seem to suggest that our Lord refused here to be guided by a mother's direction, that He wished her to understand that He was breaking off from her control and from that silent submission which He had hitherto willingly yielded."
Pulpit, 82



3)The correction - "Mine hour is not yet come."

Our Lord did not tell Mary that He would not work a miracle.  But He would have her to know that she must not expect Him to do mighty works to please His relatives after the flesh.  He would only work a miracle, upon this or any other occasion, when the fitting season for it, the time appointed in God's counsel, had arrived."
 Ryle, 89




4d.The miracle (2:6-10)






2c.John's analysis of the SIGNIFICANCE of this miracle (2:11)

1d.It was the beginning of Jesus' signs.


2d.It manifested forth His glory.


3d.It caused His disciples to believe on Him.



In this connection, recall the “Important Insight” relative to miracles in Jesus’ ministry:

The purpose of Jesus’ many miracles was to prove true His remarkable claims concerning Himself (cf. John 3:2; Ac 2:22).
 
#21 2a.The early transfer from Nazareth to Capernaum (Jn 2:12; cf. Mt 4:13)

1b.This move was clearly strategic to Jesus’ ministry

1c.The immediate practical strategy:



2c.The longer term apologetic strategy:







2b.Notice that Jesus took His family with Him, which means this was a dramatic and unusual change of life for Him and His family.



Review of Jesus’ Ministry to this point:
NOTE: It will perhaps be helpful to review the movements of Jesus from His baptism to this point.  Recall that the events of this period of Jesus' ministry are recorded only by John; the Synop¬tists all move quickly and immediately from the Temptation of Jesus to the opening of the Galilean Ministry.

However, in the Gospel of John we discover that Jesus did not in fact go directly from the Temptation to the Galilean Ministry; there was a period of several months in that interim during which Jesus' activities might be summarized as follows:

1.)After His baptism by John in the Jordan River (at a wadi just north of  the Dead Sea) the Spirit “drove” Jesus into the wilderness (desolate area on the western shore of the Dead Sea) to endure a debilitating 40-day fast and then concentrated, intense tempting by Satan. After He had resisted all of the Devil’s solicitations to evil, Jesus was ministered to by angels for some weeks in order to restore His health.

2.)John continued to minister, proclaiming that the Messiah was “in your midst,” but not knowing where He was until – just a day after the Jewish leaders had finally come to confront John about His ministry & message – Jesus emerged the wilderness and John announced, “Behold the Lamb of God,” thus signaling the beginning of Jesus’ public ministry.

3)The 4th Gospel records the 1st 5 days of Jesus: Day 1 – John announces Jesus as Messiah (Jn 1:29-34); Day 2 – John directs 2 of his disciples to follow Jesus (Jn 1:35-42); Day 3 – Jesus meets Nathanael, sets off for Galilee with some disciples (Jn 1:43-41); Day 5 – a wedding in Cana, Jesus’ 1st miracle (Jn 2:1-11).

4)Briefly to Capernaum, settles His family there, to be HQ for ministry in Galilee (2:12)

We are at this point in our study!

5)Jesus will return to Judea, go up to Jerusalem for the 1st of 4 Passovers during His ministry, will cleanse the temple for the first of two times (cf. the cleansing at the 4th & final Passover of His ministry, recorded in all 3 Synoptics).
 
#223a.Jesus asserts His messianic autho¬rity by cleansing the Temple
(Jn 2:13-22)

1b.Note the chronological notation of 2:12 – Jesus spent “not many days” getting settled in Capernaum, and then set out for Jerusalem to attend the 1st of 4 Passovers which can be discerned to have occurred during the years of His ministry.

2b.Regarding the question as to how many times Jesus cleansed the temple in the course of His ministry:

See Appendix 2.2A – How many times did Jesus cleanse the temple?

3b.The wickedness encountered by Jesus: part of the Temple area (the Court of the Gentiles) had been set aside by the Jewish authorities (Sadducees, aka chief priests), and merchants and "money changers" willing to provide a lucrative “kickback” had been allowed to "set up shop" here.

See Appendix 2.2 B – Abuses in the temple

4b.Cultural/political/religious realities important to understanding this incident

1c.With regard to the leadership of the Jewish people – everything you need to know about the Pharisees and the Sadducees!

Pharisees
Sadducees
Area of ControlSynagogueTemple
Relationship to the common manRevered and FearedDespised and Resented
Religious OrientationBelieved the Scriptures in all of its parts – including OralFunctional Unbelievers

2c.With regard to Roman officers ruling in Israel – the irreducible and non-negotiable two-fold responsibility of every Roman governor (in this case, Prefect Pontius Pilate):

1)Collect the taxes

2)Keep the peace

3c.With regard to special circumstances involved – the spectacular dynamics of Passover in Jerusalem at this stage of history:

1)The cruel burden that was Roman control (especially given the troublesome history of this people at this season)

2)Massive crowds

3)Historical remembrance (exodus from Egypt) that generated dreams of sedition


4)Specific prophetic promises which gave hope that such sedition might be at hand

4c.The Roman insistence that their constituent peoples govern their own religious affairs (Ac 18:14-16),

- the role of the Sanhedrin in that local governance of Israel (& the Jewish people), and

- the makeup of the Sanhedrin at this season of history.


5b.Jesus rids the temple courts of priestly agents – animal merchants &moneychangers (John 2:13-16)
Notes:
1)A key question: How did Jesus get away with this?
That is, how was it that Jesus was able to make such a bold move against the leaders of Judaism; why was it that the duly constituted authorities in charge of the Temple did not arrest and punish Jesus?




2.)A secondary question: momentary pique or stunning, carefully crafted strategy?

Understand the remarkable cleverness of this bold move (Mt 10:16)

a.Jesus catapulted Himself into Jewish-world-wide notoriety!

One effect of this: Jesus’ enemies could not simply seize Him and haul Him off to be stoned (as, for instance, they did Stephen later); because He was so popular, if they had done that there would have been a riot and the heads of perpetrators would roll. Therefore, it became immediately necessary to get the Romans involved in killing Jesus (see letter c. below).

b.Jesus dramatically but subtly proclaimed to that generation of Israel that He was indeed the long-awaited Messiah King of Israel –

 – but He did so in a way which would not excite the suspicion or anger of the Roman overlords (“The man put a temporary end to the thievery of the priests – who can blame him?!”), and thus made unworthy of belief any charge by His enemies that He was a threat to Rome!




c.Jesus alienated the Sadducees (chief priests), but delighted the Pharisees – thus setting the two parties of the Sanhedrin against one another, making it impossible for them to be sufficiently united to persuade the Romans to move against the Nazarene.

On the other hand, for most of the two years after this event Jesus travels from village to village throughout Galilee, teaching in the synagogues, healing all who came to Him, and offering Himself as Messiah. What specific segment of Jewish leadership is He THEN confronting and offending?

In that regard, ponder the strategy of cleansing the temple a second time on Monday of the last week of His life.

6b.During the Passover week Jesus did some miracles (2:23-25).

Note: the implication is that even after the stunning act of cleansing the temple Jesus tarried in Jerusalem through the festal week, interacted with pilgrims there, including one remarkable nocturnal interview by a prominent Sanhedrinist…

 
#23 4a.Jesus is interviewed by Nicodemus (Jn 2:23-3:31)

1b.A preliminary question: Why did Nicodemus come to Jesus?

1.)Some: Nicodemus was an official spokesman of the Sanhedrin; they had dispatched him to interrogate Jesus and to discern what ought to be their "official" reaction to Him.

2.)Better: Nicodemus seems to have been, or at least eventually to have become, an honest enquirer, one who had seen the miracles of Christ, witnessed the events at Passover, compared what he saw in Jesus to the OT Scriptures, and who now had contrived to come face-to-face with Jesus Himself - all of this in the spirit of honest "seeking after God" which God has promised to reward.

In this connection, notice the close connection in John's argument between Jn 2:23 and Jn 3:1.

Compare:

2b.Notice the effect which the miracles of Jesus had had upon Nicodemus (3:2).


3b.As Jesus dealt with Nicodemus, He stressed again the SPIRITUAL REQUIREMENTS - faith and the consequent rebirth - which all must fulfill in order to gain entrance into the kingdom of God.

**In that connection, notice the role played by Nicodemus in the Gospel of John.



#24 5a.Jesus joins forces with John the Baptist (Jn 3:22-36)

1b.The background to this event:
Even after Jesus had commenced His public ministry, John the baptizer had continued preaching in the Jordan Rift, calling upon the Jewish nation to acknowledge and accept this King who had now actually appeared and was Himself ministering in the land of Judea.  Only this element of John's ministry had c-hanged: he was no longer announcing a coming Messiah, but rather a present Messiah – Jesus of Nazareth.

2b.The character of this unappreciated period in Jesus’ early ministry
For some time (weeks? Months?) Jesus and some of His early disciples ministered near John the Baptist in the Jordan Rift, calling upon men and women to accept the message of the King and His Kingdom and to be baptized in order to prepare themselves ritually for the presence of the divine King in their midst.

1c.What might have been Jesus’ purpose in this?



2c.Again, this is often denominated “The Early Judean Ministry of Jesus,” but that title does not accurately represent this time. Jesus is not traveling to towns and villages of Judea (which He will do later in the weeks shortly before His passion); rather, He is raising up followers who will return to their villages, await His coming, and provide Him security and encouragement when He does set out on that phase of His ministry.

This often unmentioned focus of Jesus’ early ministry emphasizes the strategic importance of John’s ministry through the earlier months.



3c.The crisis which arose (3:25,26):
Sometime after the cleansing of the Temple, as Jesus was ministering in Judea and John the Baptizer continued to minister in the Jordan Rift, there was an attempt to drive a wedge between the two.  A dispute arose about the comparative efficacy and/or popularity of the ministry of John and that of Jesus.  In fact, some of the loyal followers of the Baptizer brought the question to him - they seemed to have been grieved that Jesus, the announced Messiah, was enjoying greater fruit and notoriety than was John, the announcer of the Messiah.

The response of John the Baptizer (27-36):
In the strongest terms possible, John the Baptizer insisted that a greater than himself had come, and that, in the words of John himself, "He (Jesus) must increase, but I must decrease!"


NOTE: The flow of John's narrative would strongly suggest that these words represent the final and "official" retirement of John the Baptist in his ministry as the Forerunner to the Messiah.  When John saw that his disciples were so thoroughly attached to him that they were offended by the greater popularity of the Messiah Himself, he (John the Baptist) knew that it was time for him to finally step aside.


#25 6a.Jesus leaves for Galilee via Samaria (Mt 4:12; Mk 1:14, Jn 4:1-45)

#261b.Jesus' reasons for leaving Judea (Mt 4:12; Mk 1:14; Jn 4:1-4)

1c.Note that the issue is DANGER – the Jewish leaders have somehow persuaded a Roman leader (Antipas) to move against John the Baptist, and they have heard that Jesus is having an even greater impact than that of  John.

2c.Understand well the political and demographic dynamics which caused Jesus to relocate to Galilee.



#272b.Along the way, Jesus encounters a Samaritan woman in Sychar at Jacob's well (Jn 4:5-42)

1c.It is important to understand the awful antagonism between Jew and Samaritan (cf. 4:9).

2c.Given this, it is remarkable that Jesus determined to take the rift route through Samaria (Jn 4:4).

1d.Understand the two routes from Judea to Galilee: the Ridge Route (thru Samaria) & the Rift Route (skirts Samaria on the eastern side of the Jordan River)

2d.Q: What was Jesus’ purpose in taking this more dangerous route through Samaria?

Cf. John 7:10; Luke 9:51-53;  Luke 17:11


2c.As Jesus engaged the attention of this spiritually destitute woman, He excited in her a hunger for spiritual things (4:10-15), made clear the serious¬ness of her moral condition (4:16-18), pointed out the utter futility of her present religious endeavors (4:19-24), and finally pointed her to Himself as the only answer to the needs and desires of her soul (4:25,26).

#283b.Jesus arrival in Galilee (Jn 4:43-45)

Note: John is deliberately synchronizing His Gospel with the Synoptics here (cf Mt 4:12; Mk 1:14; Lk 4:14).  It is at this point that the Synoptists resume the account of Jesus' ministry. He had spent several  months in Judea (probably 8+ months), but only the fourth Gospel records anything of that period.  Now the Lord returns to Galilee, there to commence an 18-month ministry of proclamation and demonstration.



